CREATE TABLE users (
  blockchain_account_address VARCHAR(34) PRIMARY KEY,
  nickname VARCHAR(50) NOT NULL,
  token_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE photos (
  id SERIAL PRIMARY KEY,
  hash_value VARCHAR(255) NOT NULL DEFAULT '',
  photo_url TEXT NOT NULL DEFAULT '',
  likes INTEGER NOT NULL DEFAULT 0,
  upload_status VARCHAR(20) NOT NULL DEFAULT 'Boxアップロード待ち',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);