services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - db
  #     - api
  api:
    build: ./api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=festival-app-db-user
      - DB_PASSWORD=festival-app-db-password
      - DB_NAME=mydb
    depends_on:
      - db
    ports:
      - 4000:4000
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: festival-app-db-user
      POSTGRES_PASSWORD: festival-app-db-password
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
